name: Validate Race JSON

on: [pull_request]

jobs:
  validate-github-actions-workflows:
    name: Validate GitHub Actions workflows
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: JSON Schema Validate
        uses: dsanders11/json-schema-validate-action@v1.1.0
        with:
          schema: /public/schema/races.json
          files: /public/data/races/*.json