name: Validate Race JSON

on: [pull_request]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate Race Schema
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /public/schema/races.schema.json
          INPUT_JSONS: /public/data/races/2023.json,/public/data/races/2024.json