name: Validate Race JSON

on: [pull_request]

jobs:
  validate-github-actions-workflows:
    name: Validate GitHub Actions workflows
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Ajv validate JSON(s)
        uses: vanekj/validate-json-action@v1.0.0  
        with:
          schema: public/schema/races.json
          pattern: public/data/races/*.json